pipeline {
    environment {
        registry = "moonlight234/bynet-hackaton"
        registryCredential = 'Docker_moonlight234'
        dockerImage = ''
    }
    agent any
    stages {
        stage('Cloning Git') {
            steps {
                git (
                    branch: 'main',
                    url: 'https://github.com/Moonlight17/8200-node-app.git'
                )
            }
        }
        stage('Building image') {
            steps{
                script {
                customImage = docker.build(registry + ":${BUILD_NUMBER}", "--network host .")
                }
            }
        }
        // stage('Testing image') {
        //     steps{
        //         script {
        //         customImage = docker.build(registry + ":latest", "--network host .")
        //         }
        //     }
        // }
        stage('Deploy Image') {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        customImage.push()
                    }
                }
            }
        }
    }
}