apiVersion: apps/v1
kind: Deployment
metadata:
  name: bynet-hackaton-app
  labels:
    app: bynet-hackaton
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bynet-hackaton
  template:
    metadata:
      labels:
        app: bynet-hackaton
    spec:
      containers:
        - image: moonlight234/bynet:8
          name: bynet-hackaton
          resources:
            requests:
              # memory: "64Mi"
              cpu: "10m"
            limits:
              # memory: "128Mi"
              cpu: "500m"
          ports:
            - name: project-port
              protocol: TCP
              containerPort: 3000